language: node_js
node_js:
  - 10.15.2
cache: npm install
addons:
  sonarcloud:
    organization: "opencerts"
jobs:
  include:
    - stage: sonar
      script:
        - sonar-scanner
    - stage: test
      script:
        - npm run lint
        - npm run test
    - stage: integration
      script:
        - npm run integration:headless
stages:
  - sonar
  - test
  - integration
