language: node_js
node_js:
  - "stable"
addons:
  apt:
    sources:
      - google-chrome

before_install:   
  - export TZ=Asia/Singapore

cache: npm install
script:
  - npm run lint
  - npm run test
  - npm run integration:headless
