version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:lts-browsers"
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "68:96:1e:f3:1b:10:ab:e7:52:c9:8d:11:44:00:ca:7b"
      - run:
          name: install
          command: npm ci
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
          name: build
          command: npm run build
      - run:
          name: integration
          command: ./scripts/integration-headless.sh
